version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wowanalyzer-dev
    stdin_open: true
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - .:/usr/src/wowanalyzer/
      - /usr/src/wowanalyzer/node_modules/
    environment:
      # Webpack dev server has to poll because https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-start-doesnt-detect-changes
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
