name: 'Build'

on: [push, pull_request]

env:
  CI: true

jobs:
  prepare:
    name: 'Install dependencies'
    runs-on: ubuntu-latest
    env:
      YARN_CACHE_FOLDER: .yarn-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
      - name: Get yarn cache directory path
        if: steps.cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # Use week number for automatically purging the cache every week. This is
      # useful because caching yarn-cache would otherwise lead it to grow
      # indefinitely since old dependencies are never purged.
      - name: Get week number
        if: steps.cache.outputs.cache-hit != 'true'
        id: week-number
        run: echo "::set-output name=value::$(date +%W)"
      - name: Cache "yarn-cache"
        uses: martijnhols/cache@read-only
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ steps.week-number.outputs.value }}-yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.week-number.outputs.value }}-yarn-cache-
      - run: yarn --frozen-lockfile --prefer-offline
        if: steps.cache.outputs.cache-hit != 'true'

  # TODO: Update this when possible to include the node_modules folder. GH is updating artifact action soon to make this
  #  easier (https://github.com/actions/upload-artifact/issues/7#issuecomment-566114993), and cache action multiple path
  #  support is popular (https://github.com/actions/cache/issues/16)

  typecheck:
    needs: [prepare]
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - run: yarn typecheck
  linting:
    needs: [prepare]
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - run: yarn lint --max-warnings=0
  test-interface:
    needs: [prepare]
    # This should actually include anything but parser and integration tests
    name: 'Interface tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - run: yarn test:interface --runInBand
  test-parser:
    needs: [prepare]
    name: 'Parser tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - run: yarn test:parser --runInBand
  test-integration:
    needs: [prepare]
    name: 'Integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - run: yarn test:integration --runInBand
  build:
    needs: [prepare]
    name: 'Build'
    runs-on: ubuntu-latest
    if: github.repository == 'wowanalyzer/wowanalyzer'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - name: Extract messages
        if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer'
        run: |
          yarn extract
          yarn lingui compile
      - name: Production build
        run: |
          # Needed to ignore the mini-css-extract-plugin warnings which can not be fixed with a good solution
          CI=false
          REACT_APP_ENVIRONMENT_NAME=${GITHUB_REF##*/}
          REACT_APP_VERSION=$GITHUB_SHA
          # We already ran ESLint in a separate step
          DISABLE_AUTOMATIC_ESLINT=true
          yarn build
      - run: tar -czf build.tar.gz build
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build.tar.gz
  # This only runs on PRs since it's not a part of the build step. This is
  # required as mistakes in i18n tags may trigger errors, and we skip the
  # extraction in the build for performance in PRs.
  extract-verify:
    needs: [prepare]
    name: 'Verify i18n messages'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - name: Extract messages
        run: yarn extract
      - name: Compile messages
        run: yarn lingui compile

  docker-image:
    needs: [typecheck, linting, test-interface, test-parser, test-integration, build]
    name: 'Publish Docker image'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: .
      - run: tar -xzf build.tar.gz
      # Remove files we no longer need to speed up sending context to Docker
      - run: rm build.tar.gz
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: wowanalyzer/wowanalyzer
          tag-sha: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: 'Build martijnhols/healfie:${{env.DOCKER_BUILD_TAG}}'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  # TODO: Sentry releases https://blog.sentry.io/2019/12/17/using-github-actions-to-create-sentry-releases

  extract-messages:
    needs: [prepare]
    name: 'Extract messages'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache "node_modules"
        uses: martijnhols/cache@read-only
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules3-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules3-
          read-only: true
      - name: Extract messages
        run: yarn extract
      - name: Has changes
        id: has-changes
        run: echo "::set-output name=changed::$(if [[ `git status --porcelain` ]]; then echo "true"; else echo "false"; fi)"
      - name: Commit changes
        if: steps.has-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "[skip ci] Update i18n messages" -a
      - name: Push changes
        if: steps.has-changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_BOT }}
          branch: ${{ github.ref }}

  require-changelog-entry:
    name: 'Has new changelog entry'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      YARN_CACHE_FOLDER: .yarn-cache
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --depth=1 origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: node scripts/require-changelog-entry.js
